language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
env:
  - DOCS_DEFAULT_MODULE=hex2d
script:
  - make test doc

after_success: |
  cargo doc \
  && echo '<meta http-equiv="refresh" content="0;url='${DOCS_DEFAULT_MODULE}'/index.html">' > target/doc/index.html && \
  sudo pip install ghp-import && \
  ghp-import -n target/doc && \
  git push -qf "https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" gh-pages
